[package]
name = "exeter_cycling_club"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr", "ssr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }
regex = "1.10.2"

[[bin]]
name = "exeter_cycling_club"
required-features = ["yew/csr"]
